// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `drop_preparations_for`, `err_str`, `gather_unspent`, `input_boxes_json`, `node_client`, `open_wallet`, `prepare`, `recover`, `register_handle`, `resolve_send_token`, `resolve_spend_addresses`, `session_json`, `store_preparation`, `take_preparation`, `tokens_json`, `with_handle`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedPreparation`

Future<void> setNetwork({
  required List<String> nodeUrls,
  String? explorerUrl,
}) => RustLib.instance.api.crateApiSetNetwork(
  nodeUrls: nodeUrls,
  explorerUrl: explorerUrl,
);

Future<String> probeNetwork() => RustLib.instance.api.crateApiProbeNetwork();

/// Create a wallet from a BIP-39 mnemonic. Returns `{handle_id, encrypted_seed_json, wrap_key}`.
Future<String> walletCreate({
  required String mnemonicPhrase,
  required String passphrase,
}) => RustLib.instance.api.crateApiWalletCreate(
  mnemonicPhrase: mnemonicPhrase,
  passphrase: passphrase,
);

/// Restore from a Keystore blob plus the separately stored wrap key.
/// v1 blobs that still embed `k` accept a null wrap key.
Future<BigInt> walletRestore({
  required String encryptedSeedJson,
  String? wrapKey,
}) => RustLib.instance.api.crateApiWalletRestore(
  encryptedSeedJson: encryptedSeedJson,
  wrapKey: wrapKey,
);

Future<void> walletLock({required BigInt handleId}) =>
    RustLib.instance.api.crateApiWalletLock(handleId: handleId);

Future<bool> walletIsUnlocked({required BigInt handleId}) =>
    RustLib.instance.api.crateApiWalletIsUnlocked(handleId: handleId);

Future<String> deriveAddress({required BigInt handleId, required int index}) =>
    RustLib.instance.api.crateApiDeriveAddress(
      handleId: handleId,
      index: index,
    );

Future<String> createEncryptedSeed({
  required String mnemonicPhrase,
  required String passphrase,
}) => RustLib.instance.api.crateApiCreateEncryptedSeed(
  mnemonicPhrase: mnemonicPhrase,
  passphrase: passphrase,
);

/// Seal the AES wrap key with a PIN (Argon2id + AES-GCM). Returns pin-wrap JSON.
Future<String> wrapKeyWithPin({
  required String wrapKeyHex,
  required String pin,
}) => RustLib.instance.api.crateApiWrapKeyWithPin(
  wrapKeyHex: wrapKeyHex,
  pin: pin,
);

/// Recover the AES wrap key from pin-wrap JSON.
Future<String> unwrapKeyWithPin({
  required String pinWrapJson,
  required String pin,
}) => RustLib.instance.api.crateApiUnwrapKeyWithPin(
  pinWrapJson: pinWrapJson,
  pin: pin,
);

Future<String> signReducedTransaction({
  required BigInt handleId,
  required List<int> reducedTxBytes,
}) => RustLib.instance.api.crateApiSignReducedTransaction(
  handleId: handleId,
  reducedTxBytes: reducedTxBytes,
);

Future<String> generateMnemonic({required int strength}) =>
    RustLib.instance.api.crateApiGenerateMnemonic(strength: strength);

Future<String> getBalance({required String address, String? nodeUrl}) =>
    RustLib.instance.api.crateApiGetBalance(address: address, nodeUrl: nodeUrl);

Future<String> getTokenInfo({required String tokenId, String? explorerUrl}) =>
    RustLib.instance.api.crateApiGetTokenInfo(
      tokenId: tokenId,
      explorerUrl: explorerUrl,
    );

Future<String> getTransactionHistory({
  required String address,
  String? nodeUrl,
  required BigInt limit,
  required BigInt offset,
}) => RustLib.instance.api.crateApiGetTransactionHistory(
  address: address,
  nodeUrl: nodeUrl,
  limit: limit,
  offset: offset,
);

Future<String> discoverAddresses({
  required BigInt handleId,
  String? nodeUrl,
  required int gapLimit,
}) => RustLib.instance.api.crateApiDiscoverAddresses(
  handleId: handleId,
  nodeUrl: nodeUrl,
  gapLimit: gapLimit,
);

Future<String> prepareSend({
  required BigInt handleId,
  required String senderAddress,
  required List<String> spendAddresses,
  required String changeAddress,
  required String recipientAddress,
  required PlatformInt64 amountNanoErg,
  String? tokenId,
  BigInt? tokenAmount,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiPrepareSend(
  handleId: handleId,
  senderAddress: senderAddress,
  spendAddresses: spendAddresses,
  changeAddress: changeAddress,
  recipientAddress: recipientAddress,
  amountNanoErg: amountNanoErg,
  tokenId: tokenId,
  tokenAmount: tokenAmount,
  nodeUrl: nodeUrl,
);

Future<String> listUnspentBoxes({
  required BigInt handleId,
  required List<String> addresses,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiListUnspentBoxes(
  handleId: handleId,
  addresses: addresses,
  nodeUrl: nodeUrl,
);

Future<String> sendErg({
  required BigInt handleId,
  required BigInt preparationId,
}) => RustLib.instance.api.crateApiSendErg(
  handleId: handleId,
  preparationId: preparationId,
);
