// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_custom_fee`, `drop_preparations_for`, `err_str`, `filter_selected_inputs`, `gather_unspent`, `input_boxes_json`, `node_client`, `open_wallet`, `prepare_management`, `prepare`, `recover`, `register_handle`, `resolve_send_token`, `resolve_spend_addresses`, `select_for_multi_send`, `session_json`, `sign_prepared_tx`, `store_preparation`, `take_preparation`, `tokens_json`, `with_handle`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedPreparation`, `ManagementBuild`, `ParsedRecipient`, `PreparedManagement`

Future<void> setNetwork({
  required List<String> nodeUrls,
  String? explorerUrl,
}) => RustLib.instance.api.crateApiSetNetwork(
  nodeUrls: nodeUrls,
  explorerUrl: explorerUrl,
);

Future<String> probeNetwork() => RustLib.instance.api.crateApiProbeNetwork();

/// Create a wallet from a BIP-39 mnemonic. Returns `{handle_id, encrypted_seed_json, wrap_key}`.
Future<String> walletCreate({
  required String mnemonicPhrase,
  required String passphrase,
}) => RustLib.instance.api.crateApiWalletCreate(
  mnemonicPhrase: mnemonicPhrase,
  passphrase: passphrase,
);

/// Restore from a Keystore blob plus the separately stored wrap key.
/// v1 blobs that still embed `k` accept a null wrap key.
Future<BigInt> walletRestore({
  required String encryptedSeedJson,
  String? wrapKey,
}) => RustLib.instance.api.crateApiWalletRestore(
  encryptedSeedJson: encryptedSeedJson,
  wrapKey: wrapKey,
);

Future<void> walletLock({required BigInt handleId}) =>
    RustLib.instance.api.crateApiWalletLock(handleId: handleId);

Future<bool> walletIsUnlocked({required BigInt handleId}) =>
    RustLib.instance.api.crateApiWalletIsUnlocked(handleId: handleId);

Future<String> deriveAddress({required BigInt handleId, required int index}) =>
    RustLib.instance.api.crateApiDeriveAddress(
      handleId: handleId,
      index: index,
    );

Future<String> createEncryptedSeed({
  required String mnemonicPhrase,
  required String passphrase,
}) => RustLib.instance.api.crateApiCreateEncryptedSeed(
  mnemonicPhrase: mnemonicPhrase,
  passphrase: passphrase,
);

/// Seal the AES wrap key with a PIN (Argon2id + AES-GCM). Returns pin-wrap JSON.
Future<String> wrapKeyWithPin({
  required String wrapKeyHex,
  required String pin,
}) => RustLib.instance.api.crateApiWrapKeyWithPin(
  wrapKeyHex: wrapKeyHex,
  pin: pin,
);

/// Recover the AES wrap key from pin-wrap JSON.
Future<String> unwrapKeyWithPin({
  required String pinWrapJson,
  required String pin,
}) => RustLib.instance.api.crateApiUnwrapKeyWithPin(
  pinWrapJson: pinWrapJson,
  pin: pin,
);

Future<String> signReducedTransaction({
  required BigInt handleId,
  required List<int> reducedTxBytes,
}) => RustLib.instance.api.crateApiSignReducedTransaction(
  handleId: handleId,
  reducedTxBytes: reducedTxBytes,
);

Future<String> generateMnemonic({required int strength}) =>
    RustLib.instance.api.crateApiGenerateMnemonic(strength: strength);

/// Validate an Ergo address (base58) against the checksum and network prefix.
Future<bool> validateErgoAddress({required String address}) =>
    RustLib.instance.api.crateApiValidateErgoAddress(address: address);

Future<String> getBalance({required String address, String? nodeUrl}) =>
    RustLib.instance.api.crateApiGetBalance(address: address, nodeUrl: nodeUrl);

Future<String> getTokenInfo({required String tokenId, String? explorerUrl}) =>
    RustLib.instance.api.crateApiGetTokenInfo(
      tokenId: tokenId,
      explorerUrl: explorerUrl,
    );

Future<String> getTransactionHistory({
  required String address,
  String? nodeUrl,
  required BigInt limit,
  required BigInt offset,
}) => RustLib.instance.api.crateApiGetTransactionHistory(
  address: address,
  nodeUrl: nodeUrl,
  limit: limit,
  offset: offset,
);

Future<String> discoverAddresses({
  required BigInt handleId,
  String? nodeUrl,
  required int gapLimit,
}) => RustLib.instance.api.crateApiDiscoverAddresses(
  handleId: handleId,
  nodeUrl: nodeUrl,
  gapLimit: gapLimit,
);

/// Follow a singleton token forward through spent transactions to locate the current unspent box.
///
/// Designed to work on standard nodes without extraIndex or explorer indexing.
Future<String> walkSingletonLineage({
  required String singletonTokenId,
  required String startingBoxId,
  String? nodeUrl,
  int? maxHops,
}) => RustLib.instance.api.crateApiWalkSingletonLineage(
  singletonTokenId: singletonTokenId,
  startingBoxId: startingBoxId,
  nodeUrl: nodeUrl,
  maxHops: maxHops,
);

/// Compute total balances and summary from a local WalletDatabase JSON snapshot.
Future<String> dbComputeSummary({required String dbJson}) =>
    RustLib.instance.api.crateApiDbComputeSummary(dbJson: dbJson);

Future<String> prepareSend({
  required BigInt handleId,
  required String senderAddress,
  required List<String> spendAddresses,
  required String changeAddress,
  required String recipientAddress,
  required PlatformInt64 amountNanoErg,
  String? tokenId,
  BigInt? tokenAmount,
  String? nodeUrl,
  PlatformInt64? feeNano,
}) => RustLib.instance.api.crateApiPrepareSend(
  handleId: handleId,
  senderAddress: senderAddress,
  spendAddresses: spendAddresses,
  changeAddress: changeAddress,
  recipientAddress: recipientAddress,
  amountNanoErg: amountNanoErg,
  tokenId: tokenId,
  tokenAmount: tokenAmount,
  nodeUrl: nodeUrl,
  feeNano: feeNano,
);

/// Prepare a UTXO consolidation transaction to merge multiple boxes into one.
Future<String> prepareConsolidate({
  required BigInt handleId,
  required List<String> spendAddresses,
  required List<String> selectedBoxIds,
  required String changeAddress,
  String? nodeUrl,
  PlatformInt64? feeNano,
}) => RustLib.instance.api.crateApiPrepareConsolidate(
  handleId: handleId,
  spendAddresses: spendAddresses,
  selectedBoxIds: selectedBoxIds,
  changeAddress: changeAddress,
  nodeUrl: nodeUrl,
  feeNano: feeNano,
);

/// Prepare a transaction to split ERG into N equal boxes.
Future<String> prepareSplitErg({
  required BigInt handleId,
  required List<String> spendAddresses,
  required List<String> selectedBoxIds,
  required int count,
  required PlatformInt64 amountPerBoxNano,
  required String changeAddress,
  String? nodeUrl,
  PlatformInt64? feeNano,
}) => RustLib.instance.api.crateApiPrepareSplitErg(
  handleId: handleId,
  spendAddresses: spendAddresses,
  selectedBoxIds: selectedBoxIds,
  count: count,
  amountPerBoxNano: amountPerBoxNano,
  changeAddress: changeAddress,
  nodeUrl: nodeUrl,
  feeNano: feeNano,
);

/// Prepare a transaction to split tokens into N equal boxes.
Future<String> prepareSplitToken({
  required BigInt handleId,
  required List<String> spendAddresses,
  required List<String> selectedBoxIds,
  required String tokenId,
  required int count,
  required BigInt amountPerBox,
  required PlatformInt64 ergPerBoxNano,
  required String changeAddress,
  String? nodeUrl,
  PlatformInt64? feeNano,
}) => RustLib.instance.api.crateApiPrepareSplitToken(
  handleId: handleId,
  spendAddresses: spendAddresses,
  selectedBoxIds: selectedBoxIds,
  tokenId: tokenId,
  count: count,
  amountPerBox: amountPerBox,
  ergPerBoxNano: ergPerBoxNano,
  changeAddress: changeAddress,
  nodeUrl: nodeUrl,
  feeNano: feeNano,
);

/// Prepare a custom restructure transaction to allocate specific amounts and tokens into custom output boxes.
Future<String> prepareRestructure({
  required BigInt handleId,
  required List<String> spendAddresses,
  required List<String> selectedBoxIds,
  required String outputsJson,
  required String changeAddress,
  String? nodeUrl,
  PlatformInt64? feeNano,
}) => RustLib.instance.api.crateApiPrepareRestructure(
  handleId: handleId,
  spendAddresses: spendAddresses,
  selectedBoxIds: selectedBoxIds,
  outputsJson: outputsJson,
  changeAddress: changeAddress,
  nodeUrl: nodeUrl,
  feeNano: feeNano,
);

/// List all unspent boxes (UTXOs) for the given addresses. Returns a JSON array
/// of `InputBoxInput`-compatible objects (same shape as the `input_boxes` field
/// in `prepareSend`).
Future<String> listUnspentBoxes({
  required BigInt handleId,
  required List<String> addresses,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiListUnspentBoxes(
  handleId: handleId,
  addresses: addresses,
  nodeUrl: nodeUrl,
);

Future<String> sendErg({
  required BigInt handleId,
  required BigInt preparationId,
}) => RustLib.instance.api.crateApiSendErg(
  handleId: handleId,
  preparationId: preparationId,
);

/// Sign a prepared transaction without submitting it. Returns the raw signed
/// transaction as an EIP-12 JSON string. Use this for air-gapped / raw-tx
/// export workflows.
Future<String> signPreparation({
  required BigInt handleId,
  required BigInt preparationId,
}) => RustLib.instance.api.crateApiSignPreparation(
  handleId: handleId,
  preparationId: preparationId,
);

/// Prepare a multi-recipient send. Each element of `recipients_json` is a JSON
/// object: `{"address":"...","amount_nano_erg":123,"token_id":"...","token_amount":456}`.
/// At least one recipient must carry ERG or tokens. The change goes to
/// `change_address`. Supports all `prepare_send` options (fee_nano, etc.).
Future<String> prepareSendMulti({
  required BigInt handleId,
  required String senderAddress,
  required List<String> spendAddresses,
  required String changeAddress,
  required String recipientsJson,
  String? nodeUrl,
  PlatformInt64? feeNano,
}) => RustLib.instance.api.crateApiPrepareSendMulti(
  handleId: handleId,
  senderAddress: senderAddress,
  spendAddresses: spendAddresses,
  changeAddress: changeAddress,
  recipientsJson: recipientsJson,
  nodeUrl: nodeUrl,
  feeNano: feeNano,
);
