// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `drop_preparations_for`, `err_str`, `node_config`, `open_wallet`, `prepare`, `recover`, `register_handle`, `session_json`, `store_preparation`, `take_preparation`, `with_handle`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedPreparation`

/// Create a wallet from a BIP-39 mnemonic. Returns `{handle_id, encrypted_seed_json, wrap_key}`.
Future<String> walletCreate({
  required String mnemonicPhrase,
  required String passphrase,
}) => RustLib.instance.api.crateApiWalletCreate(
  mnemonicPhrase: mnemonicPhrase,
  passphrase: passphrase,
);

/// Restore from a Keystore blob plus the separately stored wrap key.
/// v1 blobs that still embed `k` accept a null wrap key.
Future<BigInt> walletRestore({
  required String encryptedSeedJson,
  String? wrapKey,
}) => RustLib.instance.api.crateApiWalletRestore(
  encryptedSeedJson: encryptedSeedJson,
  wrapKey: wrapKey,
);

Future<void> walletLock({required BigInt handleId}) =>
    RustLib.instance.api.crateApiWalletLock(handleId: handleId);

Future<bool> walletIsUnlocked({required BigInt handleId}) =>
    RustLib.instance.api.crateApiWalletIsUnlocked(handleId: handleId);

Future<String> deriveAddress({required BigInt handleId, required int index}) =>
    RustLib.instance.api.crateApiDeriveAddress(
      handleId: handleId,
      index: index,
    );

Future<String> createEncryptedSeed({
  required String mnemonicPhrase,
  required String passphrase,
}) => RustLib.instance.api.crateApiCreateEncryptedSeed(
  mnemonicPhrase: mnemonicPhrase,
  passphrase: passphrase,
);

Future<String> signReducedTransaction({
  required BigInt handleId,
  required List<int> reducedTxBytes,
}) => RustLib.instance.api.crateApiSignReducedTransaction(
  handleId: handleId,
  reducedTxBytes: reducedTxBytes,
);

Future<String> generateMnemonic({required int strength}) =>
    RustLib.instance.api.crateApiGenerateMnemonic(strength: strength);

Future<String> getBalance({required String address, String? nodeUrl}) =>
    RustLib.instance.api.crateApiGetBalance(address: address, nodeUrl: nodeUrl);

Future<String> getTransactionHistory({
  required String address,
  String? nodeUrl,
  required BigInt limit,
}) => RustLib.instance.api.crateApiGetTransactionHistory(
  address: address,
  nodeUrl: nodeUrl,
  limit: limit,
);

Future<String> discoverAddresses({
  required BigInt handleId,
  String? nodeUrl,
  required int gapLimit,
}) => RustLib.instance.api.crateApiDiscoverAddresses(
  handleId: handleId,
  nodeUrl: nodeUrl,
  gapLimit: gapLimit,
);

Future<String> prepareSend({
  required BigInt handleId,
  required String senderAddress,
  required String recipientAddress,
  required PlatformInt64 amountNanoErg,
  String? tokenId,
  BigInt? tokenAmount,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiPrepareSend(
  handleId: handleId,
  senderAddress: senderAddress,
  recipientAddress: recipientAddress,
  amountNanoErg: amountNanoErg,
  tokenId: tokenId,
  tokenAmount: tokenAmount,
  nodeUrl: nodeUrl,
);

Future<String> sendErg({
  required BigInt handleId,
  required BigInt preparationId,
}) => RustLib.instance.api.crateApiSendErg(
  handleId: handleId,
  preparationId: preparationId,
);
