// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -918512305;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'wallet_ffi',
        ioDirectory: '../rust/crates/wallet-ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiCreateEncryptedSeed({
    required String mnemonicPhrase,
    required String passphrase,
  });

  Future<String> crateApiDbComputeSummary({required String dbJson});

  Future<String> crateApiDeriveAddress({
    required BigInt handleId,
    required int index,
  });

  Future<String> crateApiDiscoverAddresses({
    required BigInt handleId,
    String? nodeUrl,
    required int gapLimit,
  });

  Future<String> crateApiGenerateMnemonic({required int strength});

  Future<String> crateApiGetBalance({required String address, String? nodeUrl});

  Future<String> crateApiGetTokenInfo({
    required String tokenId,
    String? explorerUrl,
  });

  Future<String> crateApiGetTransactionHistory({
    required String address,
    String? nodeUrl,
    required BigInt limit,
    required BigInt offset,
  });

  Future<void> crateApiInitApp();

  Future<String> crateApiListUnspentBoxes({
    required BigInt handleId,
    required List<String> addresses,
    String? nodeUrl,
  });

  Future<String> crateApiPrepareConsolidate({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required String changeAddress,
    String? nodeUrl,
  });

  Future<String> crateApiPrepareRestructure({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required String outputsJson,
    required String changeAddress,
    String? nodeUrl,
  });

  Future<String> crateApiPrepareSend({
    required BigInt handleId,
    required String senderAddress,
    required List<String> spendAddresses,
    required String changeAddress,
    required String recipientAddress,
    required PlatformInt64 amountNanoErg,
    String? tokenId,
    BigInt? tokenAmount,
    String? nodeUrl,
  });

  Future<String> crateApiPrepareSplitErg({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required int count,
    required PlatformInt64 amountPerBoxNano,
    required String changeAddress,
    String? nodeUrl,
  });

  Future<String> crateApiPrepareSplitToken({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required String tokenId,
    required int count,
    required BigInt amountPerBox,
    required PlatformInt64 ergPerBoxNano,
    required String changeAddress,
    String? nodeUrl,
  });

  Future<String> crateApiProbeNetwork();

  Future<String> crateApiSendErg({
    required BigInt handleId,
    required BigInt preparationId,
  });

  Future<void> crateApiSetNetwork({
    required List<String> nodeUrls,
    String? explorerUrl,
  });

  Future<String> crateApiSignReducedTransaction({
    required BigInt handleId,
    required List<int> reducedTxBytes,
  });

  Future<String> crateApiUnwrapKeyWithPin({
    required String pinWrapJson,
    required String pin,
  });

  Future<String> crateApiWalkSingletonLineage({
    required String singletonTokenId,
    required String startingBoxId,
    String? nodeUrl,
    int? maxHops,
  });

  Future<String> crateApiWalletCreate({
    required String mnemonicPhrase,
    required String passphrase,
  });

  Future<bool> crateApiWalletIsUnlocked({required BigInt handleId});

  Future<void> crateApiWalletLock({required BigInt handleId});

  Future<BigInt> crateApiWalletRestore({
    required String encryptedSeedJson,
    String? wrapKey,
  });

  Future<String> crateApiWrapKeyWithPin({
    required String wrapKeyHex,
    required String pin,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiCreateEncryptedSeed({
    required String mnemonicPhrase,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicPhrase, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateEncryptedSeedConstMeta,
        argValues: [mnemonicPhrase, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateEncryptedSeedConstMeta =>
      const TaskConstMeta(
        debugName: "create_encrypted_seed",
        argNames: ["mnemonicPhrase", "passphrase"],
      );

  @override
  Future<String> crateApiDbComputeSummary({required String dbJson}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbJson, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbComputeSummaryConstMeta,
        argValues: [dbJson],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbComputeSummaryConstMeta => const TaskConstMeta(
    debugName: "db_compute_summary",
    argNames: ["dbJson"],
  );

  @override
  Future<String> crateApiDeriveAddress({
    required BigInt handleId,
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_u_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDeriveAddressConstMeta,
        argValues: [handleId, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeriveAddressConstMeta => const TaskConstMeta(
    debugName: "derive_address",
    argNames: ["handleId", "index"],
  );

  @override
  Future<String> crateApiDiscoverAddresses({
    required BigInt handleId,
    String? nodeUrl,
    required int gapLimit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          sse_encode_u_32(gapLimit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDiscoverAddressesConstMeta,
        argValues: [handleId, nodeUrl, gapLimit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDiscoverAddressesConstMeta => const TaskConstMeta(
    debugName: "discover_addresses",
    argNames: ["handleId", "nodeUrl", "gapLimit"],
  );

  @override
  Future<String> crateApiGenerateMnemonic({required int strength}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(strength, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateMnemonicConstMeta,
        argValues: [strength],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateMnemonicConstMeta => const TaskConstMeta(
    debugName: "generate_mnemonic",
    argNames: ["strength"],
  );

  @override
  Future<String> crateApiGetBalance({
    required String address,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetBalanceConstMeta,
        argValues: [address, nodeUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBalanceConstMeta => const TaskConstMeta(
    debugName: "get_balance",
    argNames: ["address", "nodeUrl"],
  );

  @override
  Future<String> crateApiGetTokenInfo({
    required String tokenId,
    String? explorerUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tokenId, serializer);
          sse_encode_opt_String(explorerUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetTokenInfoConstMeta,
        argValues: [tokenId, explorerUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTokenInfoConstMeta => const TaskConstMeta(
    debugName: "get_token_info",
    argNames: ["tokenId", "explorerUrl"],
  );

  @override
  Future<String> crateApiGetTransactionHistory({
    required String address,
    String? nodeUrl,
    required BigInt limit,
    required BigInt offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          sse_encode_u_64(limit, serializer);
          sse_encode_u_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetTransactionHistoryConstMeta,
        argValues: [address, nodeUrl, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTransactionHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "get_transaction_history",
        argNames: ["address", "nodeUrl", "limit", "offset"],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> crateApiListUnspentBoxes({
    required BigInt handleId,
    required List<String> addresses,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_list_String(addresses, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListUnspentBoxesConstMeta,
        argValues: [handleId, addresses, nodeUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListUnspentBoxesConstMeta => const TaskConstMeta(
    debugName: "list_unspent_boxes",
    argNames: ["handleId", "addresses", "nodeUrl"],
  );

  @override
  Future<String> crateApiPrepareConsolidate({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required String changeAddress,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_list_String(spendAddresses, serializer);
          sse_encode_list_String(selectedBoxIds, serializer);
          sse_encode_String(changeAddress, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareConsolidateConstMeta,
        argValues: [
          handleId,
          spendAddresses,
          selectedBoxIds,
          changeAddress,
          nodeUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareConsolidateConstMeta => const TaskConstMeta(
    debugName: "prepare_consolidate",
    argNames: [
      "handleId",
      "spendAddresses",
      "selectedBoxIds",
      "changeAddress",
      "nodeUrl",
    ],
  );

  @override
  Future<String> crateApiPrepareRestructure({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required String outputsJson,
    required String changeAddress,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_list_String(spendAddresses, serializer);
          sse_encode_list_String(selectedBoxIds, serializer);
          sse_encode_String(outputsJson, serializer);
          sse_encode_String(changeAddress, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareRestructureConstMeta,
        argValues: [
          handleId,
          spendAddresses,
          selectedBoxIds,
          outputsJson,
          changeAddress,
          nodeUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareRestructureConstMeta => const TaskConstMeta(
    debugName: "prepare_restructure",
    argNames: [
      "handleId",
      "spendAddresses",
      "selectedBoxIds",
      "outputsJson",
      "changeAddress",
      "nodeUrl",
    ],
  );

  @override
  Future<String> crateApiPrepareSend({
    required BigInt handleId,
    required String senderAddress,
    required List<String> spendAddresses,
    required String changeAddress,
    required String recipientAddress,
    required PlatformInt64 amountNanoErg,
    String? tokenId,
    BigInt? tokenAmount,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_String(senderAddress, serializer);
          sse_encode_list_String(spendAddresses, serializer);
          sse_encode_String(changeAddress, serializer);
          sse_encode_String(recipientAddress, serializer);
          sse_encode_i_64(amountNanoErg, serializer);
          sse_encode_opt_String(tokenId, serializer);
          sse_encode_opt_box_autoadd_u_64(tokenAmount, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareSendConstMeta,
        argValues: [
          handleId,
          senderAddress,
          spendAddresses,
          changeAddress,
          recipientAddress,
          amountNanoErg,
          tokenId,
          tokenAmount,
          nodeUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareSendConstMeta => const TaskConstMeta(
    debugName: "prepare_send",
    argNames: [
      "handleId",
      "senderAddress",
      "spendAddresses",
      "changeAddress",
      "recipientAddress",
      "amountNanoErg",
      "tokenId",
      "tokenAmount",
      "nodeUrl",
    ],
  );

  @override
  Future<String> crateApiPrepareSplitErg({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required int count,
    required PlatformInt64 amountPerBoxNano,
    required String changeAddress,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_list_String(spendAddresses, serializer);
          sse_encode_list_String(selectedBoxIds, serializer);
          sse_encode_u_32(count, serializer);
          sse_encode_i_64(amountPerBoxNano, serializer);
          sse_encode_String(changeAddress, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareSplitErgConstMeta,
        argValues: [
          handleId,
          spendAddresses,
          selectedBoxIds,
          count,
          amountPerBoxNano,
          changeAddress,
          nodeUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareSplitErgConstMeta => const TaskConstMeta(
    debugName: "prepare_split_erg",
    argNames: [
      "handleId",
      "spendAddresses",
      "selectedBoxIds",
      "count",
      "amountPerBoxNano",
      "changeAddress",
      "nodeUrl",
    ],
  );

  @override
  Future<String> crateApiPrepareSplitToken({
    required BigInt handleId,
    required List<String> spendAddresses,
    required List<String> selectedBoxIds,
    required String tokenId,
    required int count,
    required BigInt amountPerBox,
    required PlatformInt64 ergPerBoxNano,
    required String changeAddress,
    String? nodeUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_list_String(spendAddresses, serializer);
          sse_encode_list_String(selectedBoxIds, serializer);
          sse_encode_String(tokenId, serializer);
          sse_encode_u_32(count, serializer);
          sse_encode_u_64(amountPerBox, serializer);
          sse_encode_i_64(ergPerBoxNano, serializer);
          sse_encode_String(changeAddress, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPrepareSplitTokenConstMeta,
        argValues: [
          handleId,
          spendAddresses,
          selectedBoxIds,
          tokenId,
          count,
          amountPerBox,
          ergPerBoxNano,
          changeAddress,
          nodeUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareSplitTokenConstMeta => const TaskConstMeta(
    debugName: "prepare_split_token",
    argNames: [
      "handleId",
      "spendAddresses",
      "selectedBoxIds",
      "tokenId",
      "count",
      "amountPerBox",
      "ergPerBoxNano",
      "changeAddress",
      "nodeUrl",
    ],
  );

  @override
  Future<String> crateApiProbeNetwork() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiProbeNetworkConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeNetworkConstMeta =>
      const TaskConstMeta(debugName: "probe_network", argNames: []);

  @override
  Future<String> crateApiSendErg({
    required BigInt handleId,
    required BigInt preparationId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_u_64(preparationId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSendErgConstMeta,
        argValues: [handleId, preparationId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendErgConstMeta => const TaskConstMeta(
    debugName: "send_erg",
    argNames: ["handleId", "preparationId"],
  );

  @override
  Future<void> crateApiSetNetwork({
    required List<String> nodeUrls,
    String? explorerUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(nodeUrls, serializer);
          sse_encode_opt_String(explorerUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetNetworkConstMeta,
        argValues: [nodeUrls, explorerUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetNetworkConstMeta => const TaskConstMeta(
    debugName: "set_network",
    argNames: ["nodeUrls", "explorerUrl"],
  );

  @override
  Future<String> crateApiSignReducedTransaction({
    required BigInt handleId,
    required List<int> reducedTxBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          sse_encode_list_prim_u_8_loose(reducedTxBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSignReducedTransactionConstMeta,
        argValues: [handleId, reducedTxBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSignReducedTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "sign_reduced_transaction",
        argNames: ["handleId", "reducedTxBytes"],
      );

  @override
  Future<String> crateApiUnwrapKeyWithPin({
    required String pinWrapJson,
    required String pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(pinWrapJson, serializer);
          sse_encode_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiUnwrapKeyWithPinConstMeta,
        argValues: [pinWrapJson, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUnwrapKeyWithPinConstMeta => const TaskConstMeta(
    debugName: "unwrap_key_with_pin",
    argNames: ["pinWrapJson", "pin"],
  );

  @override
  Future<String> crateApiWalkSingletonLineage({
    required String singletonTokenId,
    required String startingBoxId,
    String? nodeUrl,
    int? maxHops,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(singletonTokenId, serializer);
          sse_encode_String(startingBoxId, serializer);
          sse_encode_opt_String(nodeUrl, serializer);
          sse_encode_opt_box_autoadd_u_32(maxHops, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalkSingletonLineageConstMeta,
        argValues: [singletonTokenId, startingBoxId, nodeUrl, maxHops],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalkSingletonLineageConstMeta =>
      const TaskConstMeta(
        debugName: "walk_singleton_lineage",
        argNames: ["singletonTokenId", "startingBoxId", "nodeUrl", "maxHops"],
      );

  @override
  Future<String> crateApiWalletCreate({
    required String mnemonicPhrase,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonicPhrase, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletCreateConstMeta,
        argValues: [mnemonicPhrase, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletCreateConstMeta => const TaskConstMeta(
    debugName: "wallet_create",
    argNames: ["mnemonicPhrase", "passphrase"],
  );

  @override
  Future<bool> crateApiWalletIsUnlocked({required BigInt handleId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletIsUnlockedConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletIsUnlockedConstMeta => const TaskConstMeta(
    debugName: "wallet_is_unlocked",
    argNames: ["handleId"],
  );

  @override
  Future<void> crateApiWalletLock({required BigInt handleId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handleId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletLockConstMeta,
        argValues: [handleId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletLockConstMeta =>
      const TaskConstMeta(debugName: "wallet_lock", argNames: ["handleId"]);

  @override
  Future<BigInt> crateApiWalletRestore({
    required String encryptedSeedJson,
    String? wrapKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(encryptedSeedJson, serializer);
          sse_encode_opt_String(wrapKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletRestoreConstMeta,
        argValues: [encryptedSeedJson, wrapKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletRestoreConstMeta => const TaskConstMeta(
    debugName: "wallet_restore",
    argNames: ["encryptedSeedJson", "wrapKey"],
  );

  @override
  Future<String> crateApiWrapKeyWithPin({
    required String wrapKeyHex,
    required String pin,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(wrapKeyHex, serializer);
          sse_encode_String(pin, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWrapKeyWithPinConstMeta,
        argValues: [wrapKeyHex, pin],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWrapKeyWithPinConstMeta => const TaskConstMeta(
    debugName: "wrap_key_with_pin",
    argNames: ["wrapKeyHex", "pin"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
