//! Ergo Wallet App/Appkit's raw BIP32 public payload (hex, no checksum).
use ergo_lib::{
    ergotree_ir::chain::address::{Address, NetworkAddress, NetworkPrefix},
    wallet::{derivation_path::ChildIndexNormal, ext_pub_key::ExtPubKey},
};

pub const EXPECTED: &str = "Expected an Ergo Wallet App extended public key: 156 hex characters, mainnet public version 0488b21e, depth 4 /0 external chain or depth 3 hardened account 0. Base58 xpub and testnet keys are not supported.";

pub fn parse(input: &str) -> Result<ExtPubKey, String> {
    let bytes = hex::decode(input.trim()).map_err(|_| EXPECTED.to_owned())?;
    if bytes.len() != 78 || bytes[..4] != [4, 0x88, 0xb2, 0x1e] || !matches!(bytes[45], 2 | 3) {
        return Err(EXPECTED.to_owned());
    }
    let path = match (bytes[4], &bytes[9..13]) {
        (4, [0, 0, 0, 0]) => "m/44'/429'/0'/0",
        (3, [0x80, 0, 0, 0]) => "m/44'/429'/0'",
        _ => return Err(EXPECTED.to_owned()),
    };
    ExtPubKey::new(
        bytes[45..78].try_into().unwrap(),
        bytes[13..45].try_into().unwrap(),
        path.parse().unwrap(),
    )
    .map_err(|_| EXPECTED.to_owned())
}

pub fn addresses(input: &str, start: u32, count: u32) -> Result<Vec<String>, String> {
    if count > 100 || start.checked_add(count).is_none_or(|end| end > 0x80000000) {
        return Err("Expected at most 100 non-hardened address indices".into());
    }
    let key = parse(input)?;
    let chain = if key.derivation_path.to_string() == "m/44'/429'/0'" {
        key.child(ChildIndexNormal::normal(0).unwrap())
    } else {
        key
    };
    Ok((start..start + count)
        .map(|i| {
            let address: Address = chain.child(ChildIndexNormal::normal(i).unwrap()).into();
            NetworkAddress::new(NetworkPrefix::Mainnet, &address).to_base58()
        })
        .collect())
}

/// Local ownership metadata, never added to the EIP-19 wire envelope.
#[derive(Debug, Clone, serde::Serialize)]
pub struct WatchAddress {
    pub address: String,
    pub index: u32,
    pub path: String,
}
#[derive(Debug, Clone, serde::Serialize)]
pub struct WatchContext {
    pub key_depth: u8,
    pub addresses: Vec<WatchAddress>,
}
impl WatchContext {
    pub fn new(input: &str, count: u32) -> Result<Self, String> {
        if count == 0 || count > 513 {
            return Err("Cold preparation supports address indices 0–512".into());
        }
        let key = parse(input)?;
        let key_depth = if key.derivation_path.to_string() == "m/44'/429'/0'" {
            3
        } else {
            4
        };
        let mut entries = Vec::new();
        for start in (0..count).step_by(100) {
            for (offset, address) in addresses(input, start, (count - start).min(100))?
                .into_iter()
                .enumerate()
            {
                let index = start + offset as u32;
                entries.push(WatchAddress {
                    address,
                    index,
                    path: format!("m/44'/429'/0'/0/{index}"),
                });
            }
        }
        Ok(Self {
            key_depth,
            addresses: entries,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ergo_lib::wallet::{ext_secret_key::ExtSecretKey, mnemonic::Mnemonic};
    // Appkit MnemonicSpec.serializeExtendedPublicKey literal, not generated by this parser.
    const KEY: &str = "0488b21e04220c2217000000009216e49a70865823eff5381d6fd33ac96743af1f3051dc4cc8edd66a29a740860326cfc301b0c8d4d815ac721e0551304417e6133c2c9137f9f22c33895a3e1650";
    #[test]
    fn appkit_export_matches_secret_chain() {
        let seed = Mnemonic::to_seed("lens stadium egg cage hollow noble gate belt impulse vicious middle endless angry buzz crack", "");
        let root = ExtSecretKey::derive_master(seed).unwrap();
        let chain = root
            .derive("m/44'/429'/0'/0".parse().unwrap())
            .unwrap()
            .public_key()
            .unwrap();
        assert_eq!(parse(KEY).unwrap(), chain);
        let context = WatchContext::new(KEY, 21).unwrap();
        assert_eq!(context.key_depth, 4);
        assert_eq!(context.addresses[20].index, 20);
        assert_eq!(context.addresses[20].path, "m/44'/429'/0'/0/20");
        assert!(WatchContext::new(KEY, 514).is_err());
        assert!(WatchContext::new(KEY, 0).is_err());
        assert_eq!(
            addresses(KEY, 0, 3).unwrap(),
            [
                "9hQ352ipFLWNA96FjCXPFidQrwp8gF4i9JUkrnxw6b4buVBFjVg",
                "9fzV11eLdVS1Mxzz59V7ewoar5FTLx7Eqfwh9XDfbL68DYTyfTv",
                "9etyztcGrJwrAbCg4d4fG9JisJLY73n69SVfpnWwuJUjy5vdbWC",
            ]
        );
        for (i, address) in addresses(KEY, 0, 20).unwrap().iter().enumerate() {
            assert_eq!(
                address,
                &crate::derivation::derive_address_from_seed(seed, i as u32).unwrap()
            );
        }
        let account = root
            .derive("m/44'/429'/0'".parse().unwrap())
            .unwrap()
            .public_key()
            .unwrap();
        let mut raw = hex::decode(KEY).unwrap();
        raw[4] = 3;
        raw[9..13].copy_from_slice(&[0x80, 0, 0, 0]);
        raw[13..45].copy_from_slice(&account.chain_code());
        raw[45..].copy_from_slice(&account.pub_key_bytes());
        assert_eq!(
            WatchContext::new(&hex::encode(&raw), 21).unwrap().key_depth,
            3
        );
        assert_eq!(
            addresses(&hex::encode(&raw), 0, 20).unwrap(),
            addresses(KEY, 0, 20).unwrap()
        );
    }
    #[test]
    fn rejects_malformed_and_wrong_path() {
        for bad in [
            "",
            "xpub123",
            &KEY[..154],
            &KEY.replacen("0488", "0435", 1),
            &KEY.replacen("1e04", "1e05", 1),
        ] {
            assert!(parse(bad).is_err());
        }
        let mut raw = hex::decode(KEY).unwrap();
        raw[45..].fill(0xff);
        assert!(parse(&hex::encode(raw)).is_err());
        assert!(addresses(KEY, 0x80000000, 1).is_err());
    }
}
