// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `busy_pool_boxes`, `check_and_sign`, `current_costs`, `default_max_legs`, `default_max_results`, `discover`, `fresh_route`, `generic`, `holding_json`, `is_chained_race`, `leg_status`, `node_err`, `parse`, `review_json`, `store_chain`, `submit_leg`, `unknown_chain`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChainRecord`, `LegSpec`, `PrepareRequest`, `ScanOptions`

/// Every arbitrage cycle the pools offer right now, best first.
///
/// `options_json`: `{"min_profit_nano", "min_depth_nano", "max_legs"?,
/// "available_nano"?, "trusted_token_ids"?, "include_untrusted"?,
/// "max_results"?}`. Reads every pool fresh and the mempool once; signs
/// nothing and needs no wallet.
Future<String> arbitrageScan({String? nodeUrl, required String optionsJson}) =>
    RustLib.instance.api.crateApiArbitrageArbitrageScan(
      nodeUrl: nodeUrl,
      optionsJson: optionsJson,
    );

/// Re-read the route, re-size it to the wallet, build every leg and check
/// the chain, refusing below `min_profit_nano`. Answers the whole chain for
/// review with a `chain_id` to execute; signs nothing.
Future<String> arbitragePrepare({
  required BigInt handleId,
  required String requestJson,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiArbitrageArbitragePrepare(
  handleId: handleId,
  requestJson: requestJson,
  nodeUrl: nodeUrl,
);

/// Forget a reviewed chain the user turned down.
void arbitrageDiscard({required BigInt chainId}) =>
    RustLib.instance.api.crateApiArbitrageArbitrageDiscard(chainId: chainId);

/// Sign every leg of a reviewed chain and broadcast them back to back.
///
/// Immediately before signing, every pool box is read again: if one is no
/// longer the box the review was built on, or a mempool transaction is
/// spending it, nothing is signed and the answer is `{"status": "moved"}`
/// so the screen can prepare and show a fresh review. Otherwise answers
/// `submitted` (every leg accepted), `rejected` (the first leg was refused;
/// nothing changed) or `stranded` (a later leg was refused; `holding`
/// names what the wallet now holds), with each accepted leg's id and
/// wallet delta.
Future<String> arbitrageExecute({
  required BigInt handleId,
  required BigInt chainId,
}) => RustLib.instance.api.crateApiArbitrageArbitrageExecute(
  handleId: handleId,
  chainId: chainId,
);

/// Where a broadcast chain stands: `complete`, `in_flight`,
/// `nothing_happened` or `stranded` (with `holding`), and each leg's
/// status. Reads only the user's node.
Future<String> arbitrageStatus({required BigInt chainId}) =>
    RustLib.instance.api.crateApiArbitrageArbitrageStatus(chainId: chainId);

/// The stranded token's sale back to ERG, as an ordinary preparation for
/// the confirm sheet and `send_erg`. Quoted against every pool as it is
/// right now; spends exactly the box the broken chain left the token in,
/// with fees from wallet boxes the chain did not spend.
Future<String> arbitragePrepareUnwind({
  required BigInt handleId,
  required BigInt chainId,
}) => RustLib.instance.api.crateApiArbitrageArbitragePrepareUnwind(
  handleId: handleId,
  chainId: chainId,
);
