// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `arriving_ids`, `check_external_inputs`, `check_stealth_inputs`, `erg_text`, `explain_for`, `explain_held`, `explain_shortfall`, `explain_with`, `forget_held_back`, `gather_spendable`, `gather_watched`, `held_back_of`, `is_empty`, `listing_json`, `mempool_or_nothing`, `nothing`, `number_after`, `owned_tree`, `read_spendable`, `record_held_back`, `settled_box_count`, `shortfall_error`, `spent_elsewhere`, `sync_inputs_json`, `sync_inputs_together`, `sync_read_in_turn`, `sync_read`, `token_in`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HeldBack`, `SyncRead`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Allow or forbid spending unconfirmed funds (incoming payments and the
/// wallet's own change). Boxes a pending transaction already spends are
/// never offered either way.
void setSpendUnconfirmed({required bool allow}) =>
    RustLib.instance.api.crateApiMempoolSetSpendUnconfirmed(allow: allow);

/// The policy coin selection currently follows.
bool spendUnconfirmed() =>
    RustLib.instance.api.crateApiMempoolSpendUnconfirmed();

/// The wallet's boxes for coin control and the UTXO tools: everything
/// spendable under the user's policy — or confirmed boxes only, when
/// `confirmed_only` — with mix reservations and mixed boxes still listed,
/// as the node lists them; the spend itself applies those rules. Each entry
/// carries its address and whether it is confirmed. Boxes a pending
/// transaction already spends are never listed.
Future<String> listSpendableBoxes({
  required BigInt handleId,
  required List<String> addresses,
  String? nodeUrl,
  required bool confirmedOnly,
}) => RustLib.instance.api.crateApiMempoolListSpendableBoxes(
  handleId: handleId,
  addresses: addresses,
  nodeUrl: nodeUrl,
  confirmedOnly: confirmedOnly,
);

/// Balances, pending activity and the pending summary for a wallet this
/// session has not unlocked, read one address at a time: the public refresh
/// of locked wallets asks the node for one thing at a time by design.
Future<String> getPublicSyncInputs({
  required List<String> addresses,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiMempoolGetPublicSyncInputs(
  addresses: addresses,
  nodeUrl: nodeUrl,
);
