// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `price_json`, `to_pool`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Options`, `PoolJson`, `TokenJson`

/// ERG prices for every token and LP token a pool set supports.
///
/// `pools_json` is the `pools` array of `amm_pools`. `options_json` is
/// `{"min_depth_nano": u64, "trusted_token_ids": [id…]}`: pools whose ERG
/// side (or a T2T pool's ERG-equivalent side) is shallower than the depth
/// are ignored, and only prices resting entirely on trusted tokens are
/// marked `trusted`.
///
/// Answers `{"tokens": {id: quote}, "lp_tokens": {id: quote}, …}` with
/// prices in nanoERG per base unit.
Future<String> pricingPoolPrices({
  required String poolsJson,
  required String optionsJson,
}) => RustLib.instance.api.crateApiPricingPricingPoolPrices(
  poolsJson: poolsJson,
  optionsJson: optionsJson,
);
