// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `basis`, `json`, `parse_tokens`, `recipient_tree`, `report_row`, `unspent_at`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Basis`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// The chain tip and the storage fee factor to judge rent by, from the
/// node's `/info`: `{height, storage_fee_factor, factor_from_node,
/// storage_period, target_block_secs}`. `factor_from_node` is false when
/// the node did not report the factor and the launch value stands in.
Future<String> rentParameters({String? nodeUrl}) =>
    RustLib.instance.api.crateApiStorageRentRentParameters(nodeUrl: nodeUrl);

/// Rent position of every confirmed unspent box at `addresses`, judged at
/// the node's tip: the [`rent_parameters`] fields plus `boxes`, one entry
/// per box with its exact serialized size, the node's fee, what a collector
/// could take (`charge`: `fee`, `whole_box` or `none`) and when.
Future<String> boxRentReport({
  required List<String> addresses,
  String? nodeUrl,
}) => RustLib.instance.api.crateApiStorageRentBoxRentReport(
  addresses: addresses,
  nodeUrl: nodeUrl,
);

/// What a recipient output carrying `tokens_json` (`[{"token_id", "amount"}]`)
/// will owe in rent if it is created at `height` with `value_nano` and never
/// moved: `{value_nano_erg, due_height, suggested_nano_erg, boxes}`.
/// `value_nano_erg` is the amount after the builders' size floor; `boxes`
/// follows their token layout (usually one box). `suggested_nano_erg` is the
/// recipient amount that lets the first box pay one charge and keep the
/// minimum box value, or null when the protocol cannot charge it.
///
/// A published stealth address is measured through a fresh one-time
/// script, which every payment to it uses in the same length.
String outputRentEstimate({
  required String address,
  required PlatformInt64 valueNano,
  required String tokensJson,
  required int height,
  required int storageFeeFactor,
}) => RustLib.instance.api.crateApiStorageRentOutputRentEstimate(
  address: address,
  valueNano: valueNano,
  tokensJson: tokensJson,
  height: height,
  storageFeeFactor: storageFeeFactor,
);
